### ISSUE TITLE
Formatting of ::TYPE makes query not valid

### ISSUE THREAD

**Issue by advoretsky** [sasha-alias/sqltabs#100]
formating of this valid (pg) query:
```
SELECT UNNEST('{"449","448"}'::BIGINT [])
```
insert space character between semicolons `: :`  making query not valid:
```
SELECT
  UNNEST('{"449","448"}': :BIGINT [])
```

**Comment by sasha-alias** [comment]
Good catch.
I've linked the issue to the library used for queries formatting.
Either we need to fix it or to find a workaround.
Thank you for reporting

**Comment by sasha-alias** [comment]
I've send a fix to the library repo https://github.com/zeroturnaround/sql-formatter/pull/24
Hopefully it will get merged soon. Expect the fix in the next release.
