### ISSUE TITLE
Not show database password in connection string

### ISSUE THREAD

**Issue by goffyara** [sasha-alias/sqltabs#105]
Remeber password, but not show for people behind you)

**Comment by sasha-alias** [comment]
Hi, if you omit password from connection string then it asks you in a separate dialog and remembers it in memory until next application restart.
If you want to have password remembered between application restarts you can add into [.pgpass file](https://www.postgresql.org/docs/current/static/libpq-pgpass.html)

**Comment by goffyara** [comment]
Is's only propose. It is inconvenient to enter password at each start. And .pgpass only for postgres.

**Comment by sasha-alias** [comment]
password dialog now can remembers passwords between app restarts
