### ISSUE TITLE
PqClient.js:110 Uncaught TypeError: res.forEach is not a function

### ISSUE THREAD

**Issue by gijs** [sasha-alias/sqltabs#114]
Hi!

I'm trying to get sqltabs up and running for development.
I checked out master and ran `npm install` and `npm start`.
When I try to connect to a PG server, I get the following error:

![screen shot 2018-04-10 at 09 50 48](https://user-images.githubusercontent.com/7193/38543382-b706f2b6-3ca4-11e8-9006-62411d2a6505.jpg)

When I console.log `res`, it shows this:

![screen shot 2018-04-10 at 09 53 30](https://user-images.githubusercontent.com/7193/38543546-19a79614-3ca5-11e8-9de5-36a7fd916b91.jpg)

Any idea?

**Comment by sasha-alias** [comment]
Hi, thanks for reporting.
Try to pull the fix.

**Comment by gijs** [comment]
Wow, never seen such a fast bugfix. Works like a charm now, thank you!
