### ISSUE TITLE
Advanced options in uri

### ISSUE THREAD

**Issue by lobster2012-user** [sasha-alias/sqltabs#124]
Hi!
MSSQL driver
Why not use the built-in parser for config?

[parser  #uri](https://github.com/tediousjs/node-mssql/blob/0bb14fdae9f00b0804932e0d446606aa31c710f3/lib/connectionstring.js)

Cannot use a trusted connection, for example.

(#104)

**Comment by sasha-alias** [comment]
Hi,
good idea actually!
rewrote to a newer driver and used built-in parser.
Will need some testing though.

**Comment by lobster2012-user** [comment]
@sasha-alias 
```js
if (parsed.query)
	{
		var ref = qs.parse(parsed.query);
		for(var key in  ref)
		{
			var dst = options;
			if(key == "driver"){
				dst = config;
			}
			dst[key] = ref[key];
		}
	}
```

I added some code. I didn’t manage to check it out, because you need to build the mssqlnodev8 binaries.

**Comment by sasha-alias** [comment]
hey, I'm not quite following what this code is intended for.
The default driver it `tedious`, so I don't think you really need to build `mssqlnodev8`.

**Comment by lobster2012-user** [comment]
@sasha-alias 
Only one driver supports trusted connection (for windows) - mssqlnodev8
Actually, this is the main reason why I created the issue. 😄
The code above allows you to specify which driver to use.

**Comment by sasha-alias** [comment]
aha, got it... it may be not that simple since this driver is not a part of default package and is windows only. I don't work with mssql, what is the advantage of having it?

**Comment by lobster2012-user** [comment]
advantage of ms sql or advantage of trusted connection ? (authentication via windows user account)
From the point of view of security and rights, it is convenient to use this type of authentication (authorization) (without entering username / password). I say, of course, about "intranet".
I will not say anything about the benefits of using ms sql.

**Comment by sasha-alias** [comment]
yeah, I was asking about trusted connection ofc :)
ok, let me think how we can do this...

**Comment by lobster2012-user** [comment]
The code above allows you to use this string.
mssql / Database.js
```js
var parse_connstr = function (connstr) {

    if (connstr.indexOf ('---')> 0) {
        connstr = connstr.split ('---') [0];
    }


    var parsed = url.parse (connstr);

    if (parsed.pathname! = 'undefined' && parsed.pathname! = null) {
        var database = parsed.pathname.substring (1);
    } else {
        var database = "";
    }

    if (parsed.auth) {
        var user = parsed.auth.split (':') [0];
        var password = parsed.auth.split (':') [1];
    } else {
        var user = '';
        var password = '';
    }

var options = {};

    var config = {
        user: user,
        password: password,
        server: parsed.hostname,
        port: parsed.port,
        options: options,
    };


if (parsed.query)
{
var ref = qs.parse (parsed.query);
for (var key in ref)
{
var dst = options;
if (key == "driver") {
dst = config;
}
dst [key] = ref [key];
}
}

    return config
}
```
mssql: //127.0.0.1: 1433 / testdb? trustedConnection = true & driver = msnodesqlv8

I repeat, I did not cope with the build yet, temporarily threw this venture.

**Comment by sasha-alias** [comment]
Hey, I believe you can try the native driver after building sqltabs from `s-mssql` branch.
The pull request is here https://github.com/sasha-alias/sqltabs/pull/126/files
I don't have windows handy to check it out, so the help here is very appreciated.

**Comment by sasha-alias** [comment]
I tried it on WIndows and getting to this issue https://github.com/TimelordUK/node-sqlserver-v8/issues/23
I guess it requires to built-in the binaries into the electron package.
I'm not sure I'm ready for this venture either :)

**Comment by lobster2012-user** [comment]
Accidentally unsubscribed from the topic.
That's right, the problem is with the build of binaries.
I finally found the old link. This problem is solved here.
https://github.com/andrewbhy/electron-sequelize-webpack

**Comment by sasha-alias** [comment]
@lobster2012-user 
hi, could you try to download and test this build please https://drive.google.com/file/d/1_rABa4lMrQYeMFI-00VdUYJuxL_lH3x0/view?usp=sharing

**Comment by lobster2012-user** [comment]
Hi, @sasha-alias . Good. I'll try at home

**Comment by lobster2012-user** [comment]
Super. The driver picked up. It remains only to consider the settings in it.

**Comment by sasha-alias** [comment]
ok, closing then
