### ISSUE TITLE
Consider adding SQL support for Cloud Firestore

### ISSUE THREAD

**Issue by rockwotj** [sasha-alias/sqltabs#129]
Hello! This is great! 

You could add SQL support for Firestore if you used on the of the following parsers:
https://github.com/forward/sql-parser
https://github.com/JavaScriptor/js-sql-parser

And translated the parsed SQL to SDK calls.

**Comment by sasha-alias** [comment]
Hi,
Thanks for the idea.
SQL Tabs is aming to provide a handy interface to DB using the native for the particular DB engine drivers. So I'm not sure how much value it would bring to have SQL interface implemented outside of Firestore.
