### ISSUE TITLE
Chart building error: ReferenceError: c3 is not defined

### ISSUE THREAD

**Issue by Macket** [sasha-alias/sqltabs#133]
I try to draw pie chart:
```
--- chart pie
SELECT id, COUNT(*) FROM users GROUP BY id
```
and get this error.

c3 installed in node_modules

**Comment by sasha-alias** [comment]
Hi, what operating system is this?

**Comment by Macket** [comment]
Hi! Ubuntu 16.04

**Comment by sasha-alias** [comment]
I guess you run it from source code.  Should be fixed now.
