### ISSUE TITLE
How to escape '@' in MySQL username when connecting

### ISSUE THREAD

**Issue by bbkane** [sasha-alias/sqltabs#156]
Hello!
I'm trying to connect to a MySQL database and my username has a `@` as part of it. When I try to connect, the app prompts for the password, then says `Error: Access denied for user 'username-before-at-symbol'@'1.1.1.1' (using password: YES)` Is there a way to escape an `@` in the username?

**Comment by sasha-alias** [comment]
Hi, sorry for delay with response.
Have you tried the standard URL escape code for @: `%40`?

**Comment by bbkane** [comment]
I'll have to try that the next time I connect, thanks!
