### ISSUE TITLE
how do I select a document in Firestore

### ISSUE THREAD

**Issue by stuurman** [sasha-alias/sqltabs#159]
I cannot get selecting one specific document to work
`collection("restaurants").doc("123").get()`

Also was wondering if selecting a specific document from a subcollection is possible?

**Comment by sasha-alias** [comment]
Is it what you need https://github.com/sasha-alias/sqltabs/issues/145#issuecomment-677728488

**Comment by stuurman** [comment]
yes, thanks. Is it also possible to select a subcollection? Like basically the equivalent of:
`collection("restaurants").doc("123").collections("menus").doc("1").get()`

Or are subcollections not supported (yet)?

**Comment by sasha-alias** [comment]
#158
