### ISSUE TITLE
Formatting and syntax highlighting for for JSON fields in PostgreSQL

### ISSUE THREAD

**Issue by vovanz** [sasha-alias/sqltabs#21]
Было бы логично отображать данные в JSON полях в PostgreSQL отформатированными и с подсветкой синтаксиса, а не просто текстом, как сейчас.

It seems logical to show JSON fields' data in PostgreSQL formatted and with highlighted syntax, not as plain text as it is now.

**Comment by sasha-alias** [comment]
good idea, thanks.
may be even not that hard to implement.
taken

**Comment by sasha-alias** [comment]
https://github.com/sasha-alias/sqldoc/commit/70bebcd1d57118dc254602294eb57fb5e4173a8e
