### ISSUE TITLE
Display SQL data type of resultset

### ISSUE THREAD

**Issue by utopic-men** [sasha-alias/sqltabs#24]
Display SQL data type for each returned column (just under the coloumn name or via tooltip for example).

Thank you for this great tool !

**Comment by sasha-alias** [comment]
Thank you for the feedback!
I can't come with a good idea how to display datatypes so that it doesn't look ugly.
The only thing I can come up with is to highlight numeric, text and timestamp values with different colours so they are recognisable.

**Comment by utopic-men** [comment]
I think having the exact type, not color, is important.

I've made a mockup :
![capture d ecran 2015-11-05 a 12 23 23](https://cloud.githubusercontent.com/assets/446969/10967093/6a149f1e-83b8-11e5-8360-c155a44434df.png)

Or use tooltips :+1: 
Thank you

**Comment by sasha-alias** [comment]
`v0.18.0` released

in order to show a datatype just click the "#" header of the datatset.
