### ISSUE TITLE
Ability to navigate through auto-complete and validate

### ISSUE THREAD

**Issue by utopic-men** [sasha-alias/sqltabs#25]
The auto-complete could be helpful if we could select and validate an item.
Or is it possible yet ???

**Comment by sasha-alias** [comment]
I'm not sure I understand the question. What does mean to validate an item?

**Comment by utopic-men** [comment]
Thank you for your response.

For example, when I start writing a table name, a contextual list appears offering me different table names.
It would be great if I can click on an list item (or select it using my keyboard : better) and it autocompletes my writing.

(Sorry for my poor english).

**Comment by olsender** [comment]
I think you are looking for Tab and Shift+Tab keyboard shortcuts, they navigate through the list and substitute the values

**Comment by utopic-men** [comment]
Yes ! Thank you ! Great !
