### ISSUE TITLE
Intermediate font size

### ISSUE THREAD

**Issue by utopic-men** [sasha-alias/sqltabs#28]
It would be nice having intermediate font size betweenSmall and X-Small :
![capture d ecran 2015-11-05 a 15 52 01](https://cloud.githubusercontent.com/assets/446969/10971568/3b23841e-83d5-11e5-98a6-1f3cc48e98f0.png)
![capture d ecran 2015-11-05 a 15 52 12](https://cloud.githubusercontent.com/assets/446969/10971569/3b24f3b2-83d5-11e5-90cb-61748b7190d5.png)

**Comment by utopic-men** [comment]
Like this (Sublime Text) :
![capture d ecran 2015-11-05 a 15 54 11](https://cloud.githubusercontent.com/assets/446969/10971624/820e1a6a-83d5-11e5-8d74-2176702bfa8d.png)

**Comment by sasha-alias** [comment]
you can customise font-size by manual editing a config file `~/.sqltabs/config.json`
just set a parameter `font-size` to a value you like, for example `150%`
