### ISSUE TITLE
Non-persistent database connexion

### ISSUE THREAD

**Issue by utopic-men** [sasha-alias/sqltabs#29]
I'm using intensively temp tables and I like to run each query step by step (block by block ;)) but the connexion is close after each run and all my temp tables are lost...

It woul be great to keep the connexion open !

**Comment by sasha-alias** [comment]
Thanks for reporting. This behaviour is not how it was supposed to work. So this is the bug which I hope to fix very soon.

**Comment by sasha-alias** [comment]
found and committed, will be available with next release

**Comment by utopic-men** [comment]
Nice ! Thank you !!
