### ISSUE TITLE
App freeze

### ISSUE THREAD

**Issue by utopic-men** [sasha-alias/sqltabs#30]
I can't determine exactly when but sometimes the app freeze (I'm navigating in SQL code using my keyboard and cursor can't move). 100% of the CPU is used !
How can I give you more info (logs, ... ?).

**Comment by sasha-alias** [comment]
What version of SQL tabs you have and which platform it is (mac/linux)?

**Comment by utopic-men** [comment]
SQL Tabs v0.11.2 on OS X El Capitan (updated).

**Comment by sasha-alias** [comment]
You can run the app from terminal like this:
```
cd SQL\ Tabs.app/Contents/MacOS/
./Electron
```
And then after the crash you will see the exception in terminal window. So it could help to understand what is causing the crash.

**Comment by sasha-alias** [comment]
there is a new version 0.12 released.
I didn't meet the app freeze for a long time already. 
Please update the issue if you still experience the problem or close it.

**Comment by sasha-alias** [comment]
Closing. Feel free to reopen the issue if still relevant.
