### ISSUE TITLE
Selection in autocomplete

### ISSUE THREAD

**Issue by egor-bayandin** [sasha-alias/sqltabs#31]
Hi!

It will be nice to have possibility to choose element in autoselect window also using arrows, not only Tab.

![2015-11-06 14-46-52 sql tabs](https://cloud.githubusercontent.com/assets/10337429/10996344/44f4f58e-8495-11e5-859b-e32bfe3e0c7f.png)

**Comment by davetoxa** [comment]
:+1:

**Comment by sasha-alias** [comment]
there were a lot of requests about that, so taken

**Comment by sasha-alias** [comment]
committed, so will be in the next release

**Comment by egor-bayandin** [comment]
Thank you! Waiting for release!

**Comment by sasha-alias** [comment]
version 0.12 released [www.sqltabs.com](www.sqltabs.com)
