### ISSUE TITLE
Installing via brew

### ISSUE THREAD

**Issue by davetoxa** [sasha-alias/sqltabs#32]
What do you think about [brew](http://brew.sh/)?

**Comment by egor-bayandin** [comment]
raise hand for this issue!

**Comment by davetoxa** [comment]
:raised_hands: 😀

**Comment by sasha-alias** [comment]
I love to use it, but have no idea how to make formulas.
And generally speaking, any help with packaging for different platforms is very appreciated.

**Comment by webervin** [comment]
currently works via [cask](https://caskroom.github.io/) `brew cask install sql-tabs`

**Comment by webervin** [comment]
as for other platforms, https://packager.io supposed to be free for open source projects. 
@sasha-alias probably can close this as "solved" for brew :)
