### ISSUE TITLE
Error during open saved connection

### ISSUE THREAD

**Issue by egor-bayandin** [sasha-alias/sqltabs#34]
Hi!

From time to time system show following error when i try to open saved connection from the list:
>Error: could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"?

**Comment by egor-bayandin** [comment]
Found one possible way to reproduce it:
- closing all spend tabs
- add new tab
- try to choose connection from list

**Comment by sasha-alias** [comment]
version 0.12 released [www.sqltabs.com](www.sqltabs.com)
