### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by rhysallister** [sasha-alias/sqltabs#35]
Supporting ssl connections would be nice.

**Comment by kaizensoze** [comment]
letsencrypt makes it fairly trivial to add ssl: https://github.com/letsencrypt/letsencrypt

**Comment by sasha-alias** [comment]
My belief is SQL Tabs supports a native SSL connection since it uses a libpq driver beneath.
I have never tested it, but it should be a matter of forming a proper connection string http://www.postgresql.org/docs/9.3/static/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by rhysallister** [comment]
I get the following when I try and force ssl by using sslmode=require:

`Error: sslmode value "require" invalid when SSL support is not compiled in`

**Comment by PJMODOS** [comment]
Means the libpq used by SQL Tabs needs to be re-compiled with SSL support.

**Comment by sasha-alias** [comment]
I believe it should be fixed in latest release.
I tried connecting to heroku with `ssl=true` and it works.
Closing the issue.
