### ISSUE TITLE
Connection was terminated. Try to restart query.

### ISSUE THREAD

**Issue by tomwys** [sasha-alias/sqltabs#36]
Version: 0.11.2
OS: Ubuntu utopic

How to reproduce:
* click "Database Info"
* wait a while
* click "public"
* error occures
* click "Database Info"
* error still occures
* click ctrl+e (any query)
* query executes correctly
* click "Database Info"
* no error

It seams that:
* clicking on "public" schema breaks connection for some reason.
* clicking "Database Info" never reconnects to valid state
* executing any valid query reconnects to valid state.

**Comment by sasha-alias** [comment]
Yep, I recently refactored that part since there were bugs regarding connections.
Let's wait for a new release and recheck if it's fixed. I will make an extra comment here once it's released.

**Comment by sasha-alias** [comment]
version 0.12 released [www.sqltabs.com](www.sqltabs.com)
