### ISSUE TITLE
Frozen/locked column headings

### ISSUE THREAD

**Issue by drewwed** [sasha-alias/sqltabs#37]
When I execute queries that return many rows, it would be nice if the column headings stayed visible as I scrolled down.  This is particularly relevant when you've got multiple foreign keys right next to each other, as it can be hard to remember which particular integer you're interested in without scrolling back to the top.

N.B. Thanks for a slick, lightweight, fast alternative to pgAdmin3!

**Comment by sasha-alias** [comment]
good idea actually, I miss column names while scrolling too.

**Comment by sasha-alias** [comment]
version 0.12 released [www.sqltabs.com](www.sqltabs.com)
