### ISSUE TITLE
Please provide a Docker image/Dockerfile for quick evaluating :)

### ISSUE THREAD

**Issue by kmoppel** [sasha-alias/sqltabs#38]
Got an error on step 4 of the building instructions "gyp_main.py: error: no such option: --no-parallel"

**Comment by sasha-alias** [comment]
I have updated README, there were missing and not accurate steps.
I'm not sure what we will gain with having docker atm. I need to check manually the functionality of GUI on  different platforms, so I can't just rely on docker build.

**Comment by sasha-alias** [comment]
I have created a separate [issue](https://github.com/sasha-alias/sqltabs/issues/39) to discuss problems with building from source code. Let's move there...
