### ISSUE TITLE
Issue with building from sources

### ISSUE THREAD

**Issue by sasha-alias** [sasha-alias/sqltabs#39]
Please, report here any issues with building from sources.

**Comment by kmoppel** [comment]
Still no luck on Ubuntu 14.04 64bit - "gyp_main.py: error: no such option: --no-parallel gyp ERR! configure error ". Sounds like some dependency hell...so I'd still vote for somekind of Docker image :)

npm install
-
> libpq@1.6.4 install /ssd/code/pgtools/sqltabs/node_modules/libpq
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /ssd/code/pgtools/sqltabs/node_modules/libpq
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by sasha-alias** [comment]
Try to follow the troubleshooting steps I described here https://github.com/sasha-alias/sqltabs/issues/41#issuecomment-167795429

**Comment by sasha-alias** [comment]
SQL Tabs switched to javascript drivers, it simplified building a lot.
Closing this thread

**Comment by Tommydreamer57** [comment]
Hey there, I think this is where my question belongs.

I get the error `‘uv_tcp_init_ex’ was not declared in this scope` in "../deps/grpc/src/core/lib/iomgr/tcp_uv.cc" when running npm install for the first time in the repository.

I'm using Ubuntu 19.04, 64bit.

```
npm i
...
../deps/grpc/src/core/lib/iomgr/tcp_uv.cc: In function ‘grpc_error* uv_socket_init_helper(uv_socket_t*, int)’:
../deps/grpc/src/core/lib/iomgr/tcp_uv.cc:190:16: error: ‘uv_tcp_init_ex’ was not declared in this scope
   int status = uv_tcp_init_ex(uv_default_loop(), tcp, (unsigned int)domain);
                ^~~~~~~~~~~~~~
../deps/grpc/src/core/lib/iomgr/tcp_uv.cc:190:16: note: suggested alternative: ‘uv_tcp_init’
   int status = uv_tcp_init_ex(uv_default_loop(), tcp, (unsigned int)domain);
                ^~~~~~~~~~~~~~
                uv_tcp_init
make: *** [grpc.target.mk:482: Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_uv.o] Error 1
make: Leaving directory '/home/tommydreamer57/Development/sqltabs/node_modules/@firebase/firestore/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
...
```

Any ideas what I can do?

**Comment by sasha-alias** [comment]
Hi, might be related to the version of nodejs you have installed.
Check `node --version`. It shouldn't be higher than 10.

**Comment by Tommydreamer57** [comment]
Hey thanks, I downgraded to node 10.16.0 (with npm 6.9.0) got it to install and run, but now I'm getting an error in the console that says "Cannot find module './build/App.js'"

I tried running the build script as well as the build:linux script and uninstalling/reinstalling, but every time the same error.

**Comment by sasha-alias** [comment]
@Tommydreamer57 
oh, that's my bad.
Just have sent a fix, try to pull and rerun:

```
git pull
npm run build
npm start
```

**Comment by Tommydreamer57** [comment]
Awesome it works now! Thanks!
