### ISSUE TITLE
Add support for formatting SQL Statements.

### ISSUE THREAD

**Issue by thomasdarimont** [sasha-alias/sqltabs#40]
It would be great to have support for formatting SQL statements.
There are some ATOM formatter plugins that could be adapted to sqltabs:
JS: https://atom.io/packages/atom-beautify
JS: https://atom.io/packages/format-sql
JS: https://github.com/diesire/atom-oracle-format

**Comment by wonzbak** [comment]
Yep very usefull for me too.

**Comment by sasha-alias** [comment]
already released, closing
