### ISSUE TITLE
vertical scroll bar not visible or half-visible

### ISSUE THREAD

**Issue by piotrekkr** [sasha-alias/sqltabs#45]
When table has many columns that do not fit window width vertical scroll bar is not visible. It is half-visible when I change font size to small. Window is full screen. I'm using linux mint 17.2. Screenshots below.

![sql tabs_001](https://cloud.githubusercontent.com/assets/503782/12034176/c2d8f7ea-ae2d-11e5-8431-79c1fe1eb6e3.png)
![sql tabs_002](https://cloud.githubusercontent.com/assets/503782/12034177/c2dee790-ae2d-11e5-8d6e-e4380df3f267.png)

**Comment by sasha-alias** [comment]
thanks! fix is on the way

**Comment by sasha-alias** [comment]
It was harder than I expected :) 
https://github.com/sasha-alias/sqltabs/commit/54f6050b51c87989065940841e9cdde0a506b7ba

**Comment by sasha-alias** [comment]
v0.12.2 released
closing
