### ISSUE TITLE
Missing charts when executing all blocks

### ISSUE THREAD

**Issue by wynbennett** [sasha-alias/sqltabs#48]
If I have more than one chart block in my SQLTabs script and then choose "Execute All Blocks" from the menu in order to generate a report then the ensuing charts do not show up.  Each chart shows perfectly well when executing individually using "Execute Block".

Here is my example code.  Any chart after the "Number of Requests" chart does not show up.

```sql
--- chart donut
/**
## Number of Requests
**/
SELECT label,count FROM metrics;

--- chart donut
/**
## Median Request Time
**/
SELECT label,median FROM metrics;

--- chart pie
/**
## Average Request Time
**/
SELECT label,avg FROM metrics;
```

I have also seen that the data in the displayed in the initial chart is sometimes corrupted when using "Execute All Blocks"; however, it is hard to pinpoint which cases that happens in.  This is occurring in 0.12.2 and was seen in 0.12.1 as well.

**Comment by sasha-alias** [comment]
ack, fixing

**Comment by sasha-alias** [comment]
@wynbennett Thank you for reporting the issue  
fix commit: https://github.com/sasha-alias/sqldoc/commit/546fba5522c705ca0966cc36bc03bc700cb8f8cc
v.0.12.3 released
Closing

**Comment by wynbennett** [comment]
Thanks for the fast turnaround.  It works great now!
