### ISSUE TITLE
Own Share Server

### ISSUE THREAD

**Issue by dice89** [sasha-alias/sqltabs#50]
Hi there,

I really love sql Tabs. However, I want to share viszualisations of customer sensitive data with it. Is there a possibility to easily set up an own share server.

**Comment by sasha-alias** [comment]
yes, there is a separate project [sqlshare](https://github.com/sasha-alias/sqlshare)
You need to install `sqlshare`, i.e. to create a simple prostgresql db schema for storing shared docs and run a nodejs application.
After you have it installed, when sharing a first doc in `SQL Tabs` change a URL for sharing with your server location. SQL Tabs will remember it and reuse further.

Feel free to report any installation issues here.
