### ISSUE TITLE
Vim-mode: r<space> replaces character with `space`

### ISSUE THREAD

**Issue by geoffharcourt** [sasha-alias/sqltabs#52]
On master at da75db7eef3edb618967f4faa27e01505f0e8f23 (post 0.12.2)

Steps to reproduce:
1. Put cursor over the character `s` in `EXISTS`
2. type <kbd>r</kbd><kbd>space</kbd>

result should be `EXIST `, but it's now `EXISTspace`.

(It might be worth trying to incorporate the vim-emulation from Atom's vim-mode rather than trying to chase down Vim's extremely complicated corner-cases.)

**Comment by sasha-alias** [comment]
Thanks for reporting.
SQL Tabs uses [Ace](https://ace.c9.io/#nav=about) as an editor.
Looks like this is the bug of the older version of ace, which is already fixed. I will upgrade the editor with the next release after some testing.

**Comment by sasha-alias** [comment]
[sqltabs v0.13.0 released](http://www.sqltabs.com)
