### ISSUE TITLE
Doing copy command hangs sql tabs

### ISSUE THREAD

**Issue by ojosdegris** [sasha-alias/sqltabs#55]
enter command 

      copy (select * from posts) to STDOUT;

press execute or CMD + R and sql tabs hangs with white screen with only option to force quit and restart.

**Comment by sasha-alias** [comment]
Thanks for reporting. Actually COPY wasn't supposed to work yet, but it shouldn't cause the app freeze for sure. Fixing.

**Comment by ojosdegris** [comment]
thanks, 
coming from sql server world and found sql-tabs to be amazing for starting with postgres, thank you for great product guys

**Comment by sasha-alias** [comment]
[sqltabs v0.13.0 released](http://www.sqltabs.com)
