### ISSUE TITLE
CMD-A selects every piece of text

### ISSUE THREAD

**Issue by decibel** [sasha-alias/sqltabs#56]
I was trying to grab just the text of an error message, so I already had the cursor down in the results pane. CMD-A selected _everything_, including the names of the tabs.

**Comment by mnuzzolilo** [comment]
This is a showstopper. What is the status of this?

**Comment by sasha-alias** [comment]
Sorry for a long delay with that.
Expect it in the nearest release, most probably the next week

**Comment by sasha-alias** [comment]
released
