### ISSUE TITLE
Not showing chart on mac os

### ISSUE THREAD

**Issue by tommagic** [sasha-alias/sqltabs#57]
Hello,

I have install sqltabs from the site and try to create a simple chart with the following code - 

```
/**
## title
**/
--- chart pie
select
    x,
    y
from datebase.table
where some condition
```

The markdown works good however I don't get a chart but a table. I have tried it with several chart types and I get the same thing for everything.
x is of date type or string (I tried several conversions) and y is integer.

**Comment by jirutka** [comment]
I have the same problem, also on OS X.

**Comment by egor-bayandin** [comment]
Confirm, the same problem

**Comment by sasha-alias** [comment]
I think it depends on the shortcut you use for execution.
Try to run via "Execute All Blocks" shortcut.
"Run Script" doesn't try to interpret the resultset but just displays it as is.

**Comment by tommagic** [comment]
Thanks for the clarification. That solved the issue for me.

**Comment by jirutka** [comment]
I’ve just tried to execute block instead of script and SQL Tabs frozen. I’m on P2D2 now, so I’ll try to find you and discuss it personally. :)

**Comment by sasha-alias** [comment]
Unfortunately I had to left P2D2. Just send here a query to reproduce.
There were a couple of fixes around rendering and frozen app recently. They are waiting for release.
May be you hit one of them.
