### ISSUE TITLE
Explain and Explain Analyze shortcuts

### ISSUE THREAD

**Issue by yazun** [sasha-alias/sqltabs#59]
It would be nice to have shortcuts to run explain (explain analyze) on a selection.

**Comment by yazun** [comment]
Also sharing directly plans via explain.depesz.com would be nice.

**Comment by sasha-alias** [comment]
Honestly I have never had issues with typing EXPLAIN :)
Also there is a concept that you see in output the result of what you have in editor. Thus when you share output it's clear what is the input. So separate shortcut for explain doesn't play nicely with overall concept. I will keep it for a while and think about it.

Regarding explain.depesz.com I rather think about integration with [PEV](http://tatiyants.com/postgres-query-plan-visualization/?utm_content=buffere28ad&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)

**Comment by sasha-alias** [comment]
finally it won't be neither depesz nor PEV but smth home-brewed #93 
this will allow to share query plans as any other query result via sqltabs.com

**Comment by sasha-alias** [comment]
both query plan visualisation and sharing via https://share.sqltabs.com are implemented in `v0.18.0` release.
separate shortcuts for `explain` and `explain analyze` won't be implemented
