### ISSUE TITLE
blank screen when requesting "object info" when current transaction is aborted

### ISSUE THREAD

**Issue by demikl** [sasha-alias/sqltabs#64]
How to reproduce:

    begin;
    select non_existent_function();

Then go to menu "database" -> "Object info". SQLTabs is non-responsive and only display a blank canvas.

It looks like sqltabs is reusing the same connection as the current query for its 'object info' internal query, but since this connection is in an "abort transaction" state, the internal query fails and.... boom ! :)

**Comment by sasha-alias** [comment]
Good catch, thanks for reporting!

**Comment by sasha-alias** [comment]
[sqltabs v0.13.0 released](http://www.sqltabs.com)
