### ISSUE TITLE
on demand autocompletion

### ISSUE THREAD

**Issue by the4thdoctor** [sasha-alias/sqltabs#67]
I found autocompletion useful but often it slows down my write speed.
Could be possible to add an option to turn it off or at least to have the autocompletion on demand (e.g. ctrl+a)?

thanks

**Comment by sasha-alias** [comment]
yes, will add the feature

**Comment by the4thdoctor** [comment]
hi, any chance to get this feature added in the next relase?
thanks :)

**Comment by sasha-alias** [comment]
sure, if there will be enough of new features expect new release in the second part of March

**Comment by the4thdoctor** [comment]
thanks :)

**Comment by sasha-alias** [comment]
SQL Tabs `v0.16.0` released
