### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by mahdavipanah** [sasha-alias/sqltabs#69]
It will be awesome if sqltabs support UTF-8 encoding.  

![screenshot_20160908_113529](https://cloud.githubusercontent.com/assets/1397846/18340197/e89eb8e0-75b8-11e6-89c4-1cf6207f532d.png)

**Comment by sasha-alias** [comment]
actually UTF-8 is supported and works fine for the languages I tried.
The issue can be related to the font which doesn't support the particular language, not sure... Need more details about your environment.

**Comment by sasha-alias** [comment]
as I wasn't able to reproduce closing the issue for the moment, feel free to reopen with reproducible scenario
