### ISSUE TITLE
CSV output doesn't work

### ISSUE THREAD

**Issue by Mnuzz** [sasha-alias/sqltabs#70]
Mac OSX
0.13.0

Query:
```
--- csv
select 1;
```

Also cannot simply copy and paste output. Cmd+A selects the entire window, pasting to file only does the first 100 records so I can't simply write a parser. The share result button is some sadistic slapstick humor after the fact. So I can query records but not actually use them. Would be a great tool for the NSA to prevent their contractors from stealing data, if not for the share button since sending it to the world is the only way to get results out of the system as is.

**Comment by sasha-alias** [comment]
Just checked csv output works as expected.
It generates resultset in a csv format to the output window.
I hear you about the extracting results out of the tool. I think after the fix of `cmd+A` you should be able to generate CSV and copy/paste it.
I think the best option would be the ability to export the result to the file.
