### ISSUE TITLE
Command line arguments to connect to a specific server

### ISSUE THREAD

**Issue by mimez** [sasha-alias/sqltabs#71]
Hey!

i tested sqltabs and it it seems to be a very useful helper. thanks for your work. for my personal workflow it would be very nice, if i could connect to a server by passing connection data to sql tabs at the command line (i'm on macOS). Is there a option for this?

thanks for your help
michael

**Comment by sasha-alias** [comment]
Hi, thanks for a feedback!
There is no such option yet. Not sure if it'd be really useful but we can think about it

**Comment by sasha-alias** [comment]
if you associate sqltabs with postgres links on macOS then in command line you can type `open postgres://localhost/postgres`
v0.17.0 released
