### ISSUE TITLE
upon upgrade to 0.14 I no longer get a password prompt

### ISSUE THREAD

**Issue by bwlang** [sasha-alias/sqltabs#73]
I use a string like this:
user@seqresults-db:/seqresults
I'd rather not embed my credentials, so this is a bummer.

**Comment by sasha-alias** [comment]
thanks for reporting, I will take a look shortly
as a quick workaround I'd recommend to use [.pgpass](https://www.postgresql.org/docs/9.6/static/libpq-pgpass.html) file

**Comment by bwlang** [comment]
I hope I'm not doing something stupid... i'v just upgraded to 0.14.1 
![image](https://cloud.githubusercontent.com/assets/61636/21764805/fd878cac-d632-11e6-9037-338606506c55.png)
but when I type into the connetion area
langhorst@seqresults-db/seqresults  I do not get a password prompt. 
executing the command says 

error: LDAP authentication failed for user "langhorst"
I can connect if I use a .pgpass (thanks) or a user that does not require a password.

**Comment by sasha-alias** [comment]
should be fixed in 0.14.4.
could you verify it please?
thank you

**Comment by bwlang** [comment]
seems to work now for me - Thanks!
