### ISSUE TITLE
Submission of MySQL Connector Support

### ISSUE THREAD

**Issue by poorlymac** [sasha-alias/sqltabs#74]
Hi,

Thanks for a great tool !!! I have taken a run at MySQL support and its working fairly well, the issues are:

- I couldn't get the password prompt stuff working properly, so need to set in the URI for now
- I still need to do some more of the Database Info bits
- I was trying to get the keywords from the DB with SELECT name FROM mysql.help_keyword ORDER BY 1; but the connection isn't really there at that stage so gave up and did as an manual include

Also to get it in you need to add:
add "mysql2": "^1.1.2", to package.json
add var mysql = require('./connectors/mysql/Database.js'); to Executor.js
add       } else if (connstr.indexOf('mysql://') == 0){ var db = mysql; to Executor.js in _getConnector

Is there any chance you get this into the next release ?

CHEERS
Paul
[mysql.zip](https://github.com/sasha-alias/sqltabs/files/700638/mysql.zip)

**Comment by sasha-alias** [comment]
Hi, that's great!
Thank you very much! I will take a look and include it into next release for sure.

PS
for easier contribution it's better to make a pull request https://help.github.com/articles/creating-a-pull-request/

**Comment by sasha-alias** [comment]
I have refactored the submission a bit.
So now it supports 
- password prompt
- multiple statements execution
- object names autocompletion

Also I created a separate renderer for MySQL so the objects information can be totally different than in Postgres, thus gives a bit more flexibility.
Before release it would be nice to have more Database Info bits, like constraints and indexes on tables etc...
I'm not going to release next few week so there is time.
Any testing appreciated as well as further submissions.
Thank you very much!

**Comment by poorlymac** [comment]
Hi,

Thats brilliant thanks, I will test. I also have it now in GitHub desktop as suggested and will try and create some time to add in the missing Database info bits. Much appreciated !

CHEERS
Paul

**Comment by poorlymac** [comment]
Hi,

Quick test and its working very well, awesome work!

Also FYI I started trying to add MSSQL support (I am on OSX Sierra) and it is a bit of a nightmare getting a proper stable connection :-(. If you had a play with MSSQL and get connections working properly I would happily do the other dev work. n.b. Like you did for MySQL info you would probably want to do a MSSQL renderer as well. (MSSQL 2016 is currently available in free beta for Linux and works very well)

CHEERS
Paul

**Comment by sasha-alias** [comment]
started to playing with MS SQL, I use `tedious` driver. I'm able to have a persistent connection and get single query results already. Though the driver looks a bit clumsy... struggling with errors processing and password prompt.

**Comment by sasha-alias** [comment]
fyi, just pushed MS SQL connector prototype https://github.com/sasha-alias/sqltabs/issues/79

**Comment by sasha-alias** [comment]
v0.15 released
