### ISSUE TITLE
Can't get EXPLAIN output with 0.14.1

### ISSUE THREAD

**Issue by demikl** [sasha-alias/sqltabs#76]
Since I've upgraded to 0.14 I can't get anymore the output from EXPLAIN queries. The result pane only shows "EXPLAIN" on a green background, same as any NOTICE message.

**Comment by sasha-alias** [comment]
Thanks for reporting! 
It should be fixed in 0.14.4 which is just released

**Comment by demikl** [comment]
Confirmed ! Thanks for your reactivity, and congrats for your nice app.
