### ISSUE TITLE
Special characters in hstore values should not be dropped

### ISSUE THREAD

**Issue by gjevardat** [sasha-alias/sqltabs#82]
Hello

We store some special characters in our hstores used as delimiters (in the value part).
The issue is that they are  simply ignored, filtered, leading to hard to read results.
In PgAdmin this character (Character delimiter = 27; in java) which I guess is an escape character is represented as a space.
In psql it is represented as \x1B.
The important thing is to print something just to be able to read the results.

Cheers

**Comment by yazun** [comment]
I think the last sentence should sound like
"The important thing is to print something just to be able to read the results."

I echo that psql representation for non-printable characters would be the most convenient..

**Comment by sasha-alias** [comment]
Could you provide me an easy way to reproduce it?
smth like:

``` sql 
create table test(h hstore);
insert into test values (???);
select * from t;
```

**Comment by yazun** [comment]
select format('a%sb',chr(27));

**Comment by sasha-alias** [comment]
thank you,
I figured out how to fix that, but probably needs some generic approach for all non printable characters.. bot sure yet which non printable characters should be replaced by their hex codes.

**Comment by gjevardat** [comment]
thanks, very efficient :)

**Comment by sasha-alias** [comment]
v0.15 released
