### ISSUE TITLE
Non numeric or date headers do not show up in column charts. 

### ISSUE THREAD

**Issue by phluidik** [sasha-alias/sqltabs#83]
Seems like if you try to do this:

--- csv
select "genre test" as '';
--- chart line x=2
select  total, description  from ( 
   select count(genre.description), genre.description as total 
   from movie, genre 
   where movie.genre_id = genre.id 
   group by genre.description
   order by genre.description desc
) a;

With a source sql return of: 
+--------+-------------+
| total  | description |
+--------+-------------+
|  12470 | Western     |
|  14391 | War         |
|  49325 | Thriller    |
|  10380 | Talk-Show   |
|  20517 | Sport       |
| 440420 | Short       |
|  13580 | Sci-Fi      |
|  34421 | Romance     |
|  12834 | Reality-TV  |
|   6426 | News        |
|   8092 | Mystery     |
|   8484 | Musical     |
|  24439 | Music       |
|  14286 | Horror      |
|  10011 | History     |
|   3212 | Game-Show   |
|    162 | Film-Noir   |
|   9094 | Fantasy     |
|  18975 | Family      |
| 113817 | Drama       |
| 100302 | Documentary |
|   8133 | Crime       |
|  67645 | Comedy      |
|   2452 | Biography   |
|   5773 | Animation   |
|   8298 | Adventure   |
|  14231 | Action      |
+--------+-------------+

You end up with the attached?

Labels seem to not work when not numeric or date values. 
<img width="691" alt="screen shot 2017-02-28 at 3 38 11 pm" src="https://cloud.githubusercontent.com/assets/12679126/23439556/0e3e004c-fdcc-11e6-8e0e-2e4b53e531f4.png">

**Comment by sasha-alias** [comment]
Hi, I'm not sure what is expected as a result.
I think for this type of data `pie` or `donut` or even `bar` charts are a better option.
You can check [this example](http://www.sqltabs.com/api/1.0/docs/486cbc66a7159659e96f68ce17707247?echo=true).

Though I admit that for `bar` chart it's not that easy to build when you have that many labels or labels are dynamic. I can create a row level bar chart for such case probably.

**Comment by phluidik** [comment]
If the labels are unique then you could treat such data as appropriate for
bar/line/etc.  Then you've got the best of both worlds. Being able to plot
non radial charts in this fashion would be extremely powerful.

**Comment by phluidik** [comment]
Otherwise, we have to compose a pivot query, which can be difficult with
that many dynamic label values.  Cumbersome, to say the least.  Intelligent
interpretation however, would be amazing as a feature. Unique labels and
single values, would lock right in for bar/line/axis/etc.

**Comment by sasha-alias** [comment]
totally agree, it may take some time to implement but I'm in

**Comment by phluidik** [comment]
oooh.. actually.. you already support options on the line right?  x=N, etc.
 how about pivot=1, then you just rotate the data.

some interesting column/row behaviors would come out of that :)

I do have to say though, GREAT program!  I am trying to teach some college
kids how to visualize data... this was freaking *perfect* with the *minor*
exception that we couldn't plot query results to a bar chart without heavy
pivoting.  they aren't there yet for query building, hehe.

thanks for considering to implement this... i really think it would be
wicked.

On Fri, Mar 3, 2017 at 4:50 PM, Sasha Aliashkevich <notifications@github.com

**Comment by sasha-alias** [comment]
SQL Tabs `v0.16.0` released.
See [example](http://www.sqltabs.com/api/1.0/docs/1e505aeab96865b6a59c3a3673f86283?echo=true)
Note that you need to have 3 columns in dataset. First one is for axis X, second one is for category name and the third one is a value.

**Comment by phluidik** [comment]
Wicked, will play with this soon!

**Comment by phluidik** [comment]
Thank you!
