### ISSUE TITLE
Combine crosstable with charts

### ISSUE THREAD

**Issue by maury91** [sasha-alias/sqltabs#84]
Will be amazing to be able to combine crosstable with charts.
The idea is to use crosstable to obtain a column for each category, and then use chart to display the progression of value for each category

**Comment by maury91** [comment]
This is an example of the result, obtained using a function that execute crosstable directly on SQL:

http://www.sqltabs.com/api/1.0/docs/4f2933727ee6549e2003aa8c414a30ed?echo=true

**Comment by sasha-alias** [comment]
Am I understand correctly you would want to use `--- crosstable` tag and `--- chart` tag together without using `crosstab` SQL function to achieve the same result?

**Comment by maury91** [comment]
Yes, will make easier to write the queries and will reduce the amount of resource consumption on the server.

Maybe a syntax like this should work:

```
--- crosstable
--- chart
```

PS: I've noticed that the CSV export don't work with crosstable

**Comment by maury91** [comment]
I'm not sure about this, but I think that the ability to pipe this commands can solve even this "issue": https://github.com/sasha-alias/sqltabs/issues/83

**Comment by sasha-alias** [comment]
Well, I thought about pipings but I can't come up with a good concept.
While `--- crosstable | chart` makes sense, the opposite `--- chart | crosstable` or `--- chart | chart` doesn't.
Basically here in most of the cases we don't transform dataset, but rather just specify how it should be rendered. Piping would make sense if we transform dataset itself.
I think the easiest here is to have a tag `--- crosschart` which before making a chart would do a `crosstable` transformation.

**Comment by maury91** [comment]
you are right, that can be the only possible user case, but piping can be more powerful (if exists the right tools).
--- crosstable | normalize | chart
--- crosstable | inject [avg|max|min|...] | chart 
(and other statistical tools)

but for now because that is the only user case, so looks good to me

**Comment by sasha-alias** [comment]
SQL Tabs `v0.16.0` released
[Example](http://www.sqltabs.com/api/1.0/docs/a5ebf9d2056a8ed970b25ac7ef0db634?echo=true)
Thank you for reporting and collaboration!
New ideas are very appreciated ;)
