### ISSUE TITLE
Restore closed tabs

### ISSUE THREAD

**Issue by sasha-alias** [sasha-alias/sqltabs#9]

**Comment by sasha-alias** [comment]
Finally dialog window was implemented before closing the tab.
So restoring the tab is not a priority anymore since in the worst case the query can be restored from the history in a new tab.

**Comment by garrettlancaster** [comment]
I cannot seem to copy paste from history, or figure out how to restore from history to a new tab. Is this documented somewhere?

**Comment by sasha-alias** [comment]
Press `Enter` in history and the found query will be inserted into current tab
