### ISSUE TITLE
unable to log in without password

### ISSUE THREAD

**Issue by Ygarr** [sasha-alias/sqltabs#90]
If postgresql have no login pass - impossible to log in.

**Comment by sasha-alias** [comment]
hm, just checked, login without password works fine.
My guess you have a different issue. What kind of error do you get?

**Comment by shinwang1** [comment]
Newbie question here...without user or password specified in database.yml `development:`, can I just use ? 
`postgres://localhost:3000/{dbname} `

**Comment by sasha-alias** [comment]
Thanks for the question,
Normally when you omit a username then the local operating system username is used.
But looks like in recent version of SQL Tabs there is a bug which makes a username `null` if it's not present in the connection string.
I'm going to fix it.

**Comment by sasha-alias** [comment]
v0.17.0 released
please check and reopen the ticket if the issue is still present
