### ISSUE TITLE
Customisable colours for each connection

### ISSUE THREAD

**Issue by maury91** [sasha-alias/sqltabs#91]
Being able to choose a colour for every different connection saved in the drop-down menu.
The color will be displayed in a visible place while the connection is in use.

The goal is to provide a fast visual feedback about the connection that is used. For example, for a live environment, a good colour choice is red, in this way the user knows with a look that is in a dangerous environment and should give extra attention.

**Comment by sasha-alias** [comment]
I've started to work on this, please let met know in case you have smth already...

**Comment by maury91** [comment]
for the design I was thinking something simple, like this:
![screen shot 2017-04-20 at 10 50 28](https://cloud.githubusercontent.com/assets/4061875/25224758/4255da0e-25b7-11e7-9e1c-045f7760c90e.png)

I obtained that with the by changing the styles of the following:
_body > div > div.tab-navigator > nav > ul > li.active > a_
```css
    background-color: #ff7777;
```

_body > div > div.tab-container > div_
```css
    border-top: 3px solid #ff7777;
    border-radius: 3px;
```

**Comment by sasha-alias** [comment]
Haha :) 👍 
I just was thinking about string like this as well `--- Tab Name #abc`
But it doesn't look very user friendly, this is what I'm thinking of now
Color picker is in the very end of connection string input. And only a toolbar is colorised:

<img width="878" alt="screen shot 2017-04-20 at 12 07 03" src="https://cloud.githubusercontent.com/assets/6050265/25225621/5b84d3c6-25c2-11e7-886f-979e0e2903a2.png">

**Comment by sasha-alias** [comment]
<img width="845" alt="screen shot 2017-04-22 at 16 28 38" src="https://cloud.githubusercontent.com/assets/6050265/25305300/005382dc-2779-11e7-8fa9-8b91b4330aa6.png">

**Comment by sasha-alias** [comment]
This change required to upgrade React. So this commit is pretty big and can break smth up.
Any testing before release is very appreciated.

**Comment by maury91** [comment]
I've found an UI issue, the new icons are on top of text when you write the connection string, adding some padding-right to the input box should solve the problem

**Comment by sasha-alias** [comment]
good catch! will add padding to connection input
thanks

**Comment by sasha-alias** [comment]
v0.17.0 released
