### ISSUE TITLE
Ability to reconnect

### ISSUE THREAD

**Issue by dayfuaim** [sasha-alias/sqltabs#92]
Please, make the possibility to reconnect to DB after some timeout as shortcut.
Currently, it could be done after _random_ (sometimes first, sometimes second etc.) time of pressing `<Enter>` on connect input string. Sometimes, I have to restart the whole app.

**Comment by sasha-alias** [comment]
I think to open a new tab is usually enough since every tab uses a separate connection.

**Comment by dayfuaim** [comment]
I understand this, but...
Why produce entities beyond necessity?
I meant _manual_ reconnect, not automatic (IMHO it's not needed).
Just `Ctrl`+`R` – and that's it.
I think I am not alone in this. ;)

**Comment by sasha-alias** [comment]
Do you think not trying to reuse connection on `<Enter>`, but reestablishing a new one would be good enough?

**Comment by dayfuaim** [comment]
Yes, I think so.
Because I tried `Enter` not once and not thrice – there was no result.

**Comment by sasha-alias** [comment]
Shifting this to next release, sorry for delay.

**Comment by dayfuaim** [comment]
Thank you very much.
Waiting impatiently. :)

**Comment by sasha-alias** [comment]
`v0.18.0` released
