### ISSUE TITLE
Explain plan cost/time visualisation

### ISSUE THREAD

**Issue by sasha-alias** [sasha-alias/sqltabs#93]
When analysing long query plans it's often hard to get which part is the most expensive. So adding some formatting and visualisation for EXPLAIN output.
So far the development version looks like on a screenshot below.
Further ideas are very appreciated

![screen shot 2017-05-04 at 16 11 42](https://cloud.githubusercontent.com/assets/6050265/25709625/1a291bfc-30ea-11e7-846d-b2077bf0dd49.png)

**Comment by maury91** [comment]
I think the best will be a flowchart like the old SQL programs:

![Flowchart](https://docs.oracle.com/cd/B28359_01/server.111/b28275/img/sql_details_plan_graph.gif)

there's a nice library in react to create those flowcharts:
https://github.com/projectstorm/react-diagrams

**Comment by sasha-alias** [comment]
Actually I don't like much a flowchart representation of explain plan.
From my point of view it doesn't help to troubleshoot the things, especially when it's going to complicated queries with dozens of lines.
So far I added 2 diagrams to the plan nodes: inclusive cost/time and exclusive cost/time. This way it should be easier to identify from the quick look which part of the plan has the issues.
Also I've made nodes collapsible, so you are able to hide a part of the plan you are not interested in (line 9 on the picture).
And have made some text formatting for easier reading... Work is still in progress

![screen shot 2017-05-09 at 16 08 47](https://cloud.githubusercontent.com/assets/6050265/25855068/71cfcd2e-34d2-11e7-9616-23b0938fe51b.png)

**Comment by sasha-alias** [comment]
@maury91 thanks for pointing out the react-diagrams library. It looks very promising. I think it can be used for tackling ER Diagrams #20

**Comment by sasha-alias** [comment]
thanks to @tvondra there will be 2 views for explain plan :)
feedback is very appreciated
<img width="1052" alt="screen shot 2017-05-18 at 09 36 25" src="https://cloud.githubusercontent.com/assets/6050265/26191300/a4145070-3bad-11e7-9929-4ff3854f672e.png">

**Comment by tvondra** [comment]
So my nagging while drinking beer worked? We need to go for a beer more often!

**Comment by sasha-alias** [comment]
yeah 🍺  actually being more on devops side I missed the use cases of consulting DBAs, that was useful to hear. @tvondra check this out http://explain.sqltabs.com/

**Comment by sasha-alias** [comment]
`v0.18.0` released
